'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34003
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")>  _
Partial Friend NotInheritable Class TextEditorState
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As TextEditorState = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New TextEditorState()),TextEditorState)
    
    Public Shared ReadOnly Property [Default]() As TextEditorState
        Get
            Return defaultInstance
        End Get
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(), _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 8.25pt")> _
    Public Property ContentFont() As Global.System.Drawing.Font
        Get
            Return CType(Me("ContentFont"), Global.System.Drawing.Font)
        End Get
        Set(value As Global.System.Drawing.Font)
            Me("ContentFont") = value
        End Set
    End Property

    <Global.System.Configuration.UserScopedSettingAttribute(), _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.Configuration.DefaultSettingValueAttribute("True")> _
    Public Property StatusBarVisible() As Boolean
        Get
            Return CType(Me("StatusBarVisible"), Boolean)
        End Get
        Set(value As Boolean)
            Me("StatusBarVisible") = value
        End Set
    End Property

    <Global.System.Configuration.UserScopedSettingAttribute(), _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.Configuration.DefaultSettingValueAttribute("True")> _
    Public Property ContentWordWrap() As Boolean
        Get
            Return CType(Me("ContentWordWrap"), Boolean)
        End Get
        Set(value As Boolean)
            Me("ContentWordWrap") = value
        End Set
    End Property
End Class
